=== neolm2004/easyba/batools-core/src/main/JobForRepositoryConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by LM (AILK) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="JobForRepositoryConfig">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="JobName" type="xs:string"/>
				<xs:element name="JobTrigger" type="xs:string"/>
				<xs:element name="IndexFileFilter">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="IncludeExtension" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="TargetPaths">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="TargetPath" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="EntrySvnFileName" type="xs:string"/>
				<xs:element name="JobParameters">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Param" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ParamName" type="xs:string"/>
										<xs:element name="ParamValue" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== neolm2004/easyba/batools-core/src/main/resources/cscwh.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobForRepositoryConfig xsi:noNamespaceSchemaLocation="JobForRepositoryConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<JobName>csc-wh</JobName>
	<JobTrigger>0 55 * * *  ?</JobTrigger>
	<IndexFileFilter>
		<IncludeExtension>
			<Value>docx</Value>
			<Value>doc</Value>			
			<Value>txt</Value>
			<Value>xls</Value>
			<Value>xlsx</Value>
			<Value>ppt</Value>
			<Value>pptx</Value>
		</IncludeExtension>
	</IndexFileFilter>
	<TargetPaths>	
	<TargetPath>/04-解决方案/2014年/2014-01/CRM侧设计文档/</TargetPath>
	</TargetPaths>
	<EntrySvnFileName>e:\\svntry.txt</EntrySvnFileName>
	<JobParameters>
		<Param>
			<ParamName>loginname</ParamName>
			<ParamValue>lvming</ParamValue>
		</Param>
		<Param>
			<ParamName>loginpwd</ParamName>
			<ParamValue>lvming</ParamValue>
		</Param>
		<Param>
			<ParamName>maxDocNum</ParamName>
			<ParamValue>16407</ParamValue>
		</Param>
		</JobParameters>
</JobForRepositoryConfig>
